version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: telegrambot.postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TelegramBot
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  
  telegrambot.webapi:
    image: telegrambot.webapi
    build:
      context: .
      dockerfile: TelegramBot.WebAPI/Dockerfile
    container_name: telegrambot.webapi
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      ConnectionStrings__PostgresConnection: "Host=postgres;Port=5432;Username=postgres;Password=password;Database=TelegramBot;"
    volumes:
      - ./TelegramBot.WebAPI/appsettings.Development.json:/app/appsettings.Development.json
        

volumes:
  postgres_data: