version: '3.9'

services:
  telegrambot.webapi:
    image: telegrambot.webapi
    build:
      context: .
      dockerfile: TelegramBot.WebAPI/Dockerfile
    container_name: telegram
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./TelegramBot.WebAPI/appsettings.Development.json:/app/appsettings.Development.json